package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.model.ExportFile;
import cn.kemis.model.ExportFileExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

import java.util.List;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table export_file
 *
 * @mbggenerated Sat Aug 20 22:05:13 CST 2016
 */
@Mapper
public interface ExportFileMapper extends BaseMapper<ExportFile, ExportFileExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    int countByExample(ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    int deleteByExample(ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    @Delete({
        "delete from export_file",
        "where exportFileId = #{exportFileId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long exportFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    @Insert({
        "insert into export_file (batchNo, fileName, ",
        "fileSuffix, fileGuid, ",
        "fileUrl, `type`, `status`, ",
        "createTime, updateTime)",
        "values (#{batchNo,jdbcType=VARCHAR}, #{fileName,jdbcType=VARCHAR}, ",
        "#{fileSuffix,jdbcType=VARCHAR}, #{fileGuid,jdbcType=VARCHAR}, ",
        "#{fileUrl,jdbcType=VARCHAR}, #{type,jdbcType=CHAR}, #{status,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="exportFileId", before=false, resultType=Integer.class)
    int insert(ExportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    int insertSelective(ExportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    List<ExportFile> selectByExample(ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    @Select({
        "select",
        "exportFileId, batchNo, fileName, fileSuffix, fileGuid, fileUrl, `type`, `status`, ",
        "createTime, updateTime",
        "from export_file",
        "where exportFileId = #{exportFileId,jdbcType=INTEGER}"
    })
    @ResultMap("cn.kemis.dao.mapper.ExportFileMapper.BaseResultMap")
    ExportFile selectByPrimaryKey(Long exportFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") ExportFile record, @Param("example") ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    int updateByExample(@Param("record") ExportFile record, @Param("example") ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    int updateByPrimaryKeySelective(ExportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbggenerated Sat Aug 20 22:05:13 CST 2016
     */
    @Update({
        "update export_file",
        "set batchNo = #{batchNo,jdbcType=VARCHAR},",
          "fileName = #{fileName,jdbcType=VARCHAR},",
          "fileSuffix = #{fileSuffix,jdbcType=VARCHAR},",
          "fileGuid = #{fileGuid,jdbcType=VARCHAR},",
          "fileUrl = #{fileUrl,jdbcType=VARCHAR},",
          "`type` = #{type,jdbcType=CHAR},",
          "`status` = #{status,jdbcType=TINYINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where exportFileId = #{exportFileId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ExportFile record);
}