package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.model.PersistentLogins;
import cn.kemis.model.PersistentLoginsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import org.apache.ibatis.annotations.Mapper;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table persistent_logins
 *
 * @mbggenerated Wed Aug 03 23:17:35 CST 2016
 */
@Mapper
public interface PersistentLoginsMapper extends BaseMapper<PersistentLogins, PersistentLoginsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int countByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int deleteByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Delete({
        "delete from persistent_logins",
        "where series = #{series,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Insert({
        "insert into persistent_logins (series, username, ",
        "token, last_used)",
        "values (#{series,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{token,jdbcType=VARCHAR}, #{last_used,jdbcType=TIMESTAMP})"
    })
    int insert(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int insertSelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    List<PersistentLogins> selectByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Select({
        "select",
        "series, username, token, last_used",
        "from persistent_logins",
        "where series = #{series,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.kemis.dao.mapper.PersistentLoginsMapper.BaseResultMap")
    PersistentLogins selectByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int updateByExample(@Param("record") PersistentLogins record, @Param("example") PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int updateByPrimaryKeySelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Update({
        "update persistent_logins",
        "set username = #{username,jdbcType=VARCHAR},",
          "token = #{token,jdbcType=VARCHAR},",
          "last_used = #{last_used,jdbcType=TIMESTAMP}",
        "where series = #{series,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PersistentLogins record);
}