package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.model.ReplaceKeywords;
import cn.kemis.model.ReplaceKeywordsExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table replace_keywords
 *
 * @mbggenerated Thu Aug 18 00:38:04 CST 2016
 */
@Mapper
public interface ReplaceKeywordsMapper extends BaseMapper<ReplaceKeywords, ReplaceKeywordsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    int countByExample(ReplaceKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    int deleteByExample(ReplaceKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    @Delete({
        "delete from replace_keywords",
        "where replaceKeywordsId = #{replaceKeywordsId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer replaceKeywordsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    @Insert({
        "insert into replace_keywords (replaceKeywordsId, keyword, ",
        "`type`, `status`, createTime, ",
        "updateTime)",
        "values (#{replaceKeywordsId,jdbcType=INTEGER}, #{keyword,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=CHAR}, #{status,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(ReplaceKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    int insertSelective(ReplaceKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    List<ReplaceKeywords> selectByExample(ReplaceKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    @Select({
        "select",
        "replaceKeywordsId, keyword, `type`, `status`, createTime, updateTime",
        "from replace_keywords",
        "where replaceKeywordsId = #{replaceKeywordsId,jdbcType=INTEGER}"
    })
    @ResultMap("cn.kemis.dao.mapper.ReplaceKeywordsMapper.BaseResultMap")
    ReplaceKeywords selectByPrimaryKey(Integer replaceKeywordsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ReplaceKeywords record, @Param("example") ReplaceKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    int updateByExample(@Param("record") ReplaceKeywords record, @Param("example") ReplaceKeywordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    int updateByPrimaryKeySelective(ReplaceKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replace_keywords
     *
     * @mbggenerated Thu Aug 18 00:38:04 CST 2016
     */
    @Update({
        "update replace_keywords",
        "set keyword = #{keyword,jdbcType=VARCHAR},",
          "`type` = #{type,jdbcType=CHAR},",
          "`status` = #{status,jdbcType=TINYINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where replaceKeywordsId = #{replaceKeywordsId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ReplaceKeywords record);

    @Select({
            "select",
            "replaceKeywordsId, keyword, `type`, `status`, createTime, updateTime",
            "from replace_keywords",
            "where keyword = #{keyword,jdbcType=VARCHAR} and type = #{type,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.kemis.dao.mapper.ReplaceKeywordsMapper.BaseResultMap")
    ReplaceKeywords selectByKeyword(@Param("keyword")String keyword, @Param("type")String type);
}