package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.domain.SysRoleDomain;
import cn.kemis.model.SysRole;
import cn.kemis.model.SysRoleExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 *
 * @mbggenerated Thu Aug 18 00:33:50 CST 2016
 */
@Mapper
public interface SysRoleMapper extends BaseMapper<SysRole, SysRoleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    int countByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    int deleteByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    @Delete({
        "delete from sys_role",
        "where sysRoleId = #{sysRoleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sysRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    @Insert({
        "insert into sys_role (sysRoleId, roleName, ",
        "roleDesc, roleParentId, ",
        "permissionName, `status`, ",
        "createTime, updateTime)",
        "values (#{sysRoleId,jdbcType=INTEGER}, #{roleName,jdbcType=VARCHAR}, ",
        "#{roleDesc,jdbcType=VARCHAR}, #{roleParentId,jdbcType=INTEGER}, ",
        "#{permissionName,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    List<SysRole> selectByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    @Select({
        "select",
        "sysRoleId, roleName, roleDesc, roleParentId, permissionName, `status`, createTime, ",
        "updateTime",
        "from sys_role",
        "where sysRoleId = #{sysRoleId,jdbcType=INTEGER}"
    })
    @ResultMap("cn.kemis.dao.mapper.SysRoleMapper.BaseResultMap")
    SysRole selectByPrimaryKey(Integer sysRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Thu Aug 18 00:33:50 CST 2016
     */
    @Update({
        "update sys_role",
        "set roleName = #{roleName,jdbcType=VARCHAR},",
          "roleDesc = #{roleDesc,jdbcType=VARCHAR},",
          "roleParentId = #{roleParentId,jdbcType=INTEGER},",
          "permissionName = #{permissionName,jdbcType=VARCHAR},",
          "`status` = #{status,jdbcType=TINYINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where sysRoleId = #{sysRoleId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysRole record);

    List<SysRoleDomain> selectRoleDomainByUserId(Integer id);

    @Select({
        "select",
        "rhs.moduleId",
        "from sys_role sr join sys_role_has_sys_module rhs on sr.sysRoleId = rhs.roleId",
        "where sr.sysRoleId = #{roleId,jdbcType=INTEGER}"
    })
    List<Integer> selectModuleIdByRoleId(int roleId);
}