package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.model.SysUserHasSysRoleExample;
import cn.kemis.model.SysUserHasSysRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import org.apache.ibatis.annotations.Mapper;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user_has_sys_role
 *
 * @mbggenerated Wed Aug 03 23:17:35 CST 2016
 */
@Mapper
public interface SysUserHasSysRoleMapper extends BaseMapper<SysUserHasSysRoleKey, SysUserHasSysRoleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int countByExample(SysUserHasSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int deleteByExample(SysUserHasSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Delete({
        "delete from sys_user_has_sys_role",
        "where userId = #{userId,jdbcType=INTEGER}",
          "and roleId = #{roleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(SysUserHasSysRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Insert({
        "insert into sys_user_has_sys_role (userId, roleId)",
        "values (#{userId,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER})"
    })
    int insert(SysUserHasSysRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int insertSelective(SysUserHasSysRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    List<SysUserHasSysRoleKey> selectByExample(SysUserHasSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysUserHasSysRoleKey record, @Param("example") SysUserHasSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_has_sys_role
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    int updateByExample(@Param("record") SysUserHasSysRoleKey record, @Param("example") SysUserHasSysRoleExample example);
}