package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.domain.SysUserDomain;
import cn.kemis.domain.UsersForSelectDomain;
import cn.kemis.model.SysUser;
import cn.kemis.model.SysUserExample;
import org.apache.ibatis.annotations.*;

import java.util.List;
/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 *
 * @mbggenerated Thu Aug 18 00:35:42 CST 2016
 */
@Mapper
public interface SysUserMapper extends BaseMapper<SysUser, SysUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    int countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    @Delete({
        "delete from sys_user",
        "where sysUserId = #{sysUserId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    @Insert({
        "insert into sys_user (sysUserId, username, ",
        "`password`, userCode, ",
        "realName, mobile, ",
        "email, address, ",
        "avatar, loginCount, ",
        "lastLogin, `status`, ",
        "createTime, updateTime)",
        "values (#{sysUserId,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{userCode,jdbcType=VARCHAR}, ",
        "#{realName,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{avatar,jdbcType=VARCHAR}, #{loginCount,jdbcType=INTEGER}, ",
        "#{lastLogin,jdbcType=TIMESTAMP}, #{status,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    @Select({
        "select",
        "sysUserId, username, `password`, userCode, realName, mobile, email, address, ",
        "avatar, loginCount, lastLogin, `status`, createTime, updateTime",
        "from sys_user",
        "where sysUserId = #{sysUserId,jdbcType=INTEGER}"
    })
    @ResultMap("cn.kemis.dao.mapper.SysUserMapper.BaseResultMap")
    SysUser selectByPrimaryKey(Integer sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    @Update({
        "update sys_user",
        "set username = #{username,jdbcType=VARCHAR},",
          "`password` = #{password,jdbcType=VARCHAR},",
          "userCode = #{userCode,jdbcType=VARCHAR},",
          "realName = #{realName,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "loginCount = #{loginCount,jdbcType=INTEGER},",
          "lastLogin = #{lastLogin,jdbcType=TIMESTAMP},",
          "`status` = #{status,jdbcType=TINYINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where sysUserId = #{sysUserId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysUser record);


    @Select({
        "SELECT sysUserId, realName FROM sys_user where status = 0 and sysUserId > 1"
    })
    @ResultType(UsersForSelectDomain.class)
    List<UsersForSelectDomain> usersForSelect();

    List<SysUserDomain> selectWithRoleByRecord(SysUser user);
}