package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.model.UploadFile;
import cn.kemis.model.UploadFileExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table upload_file
 *
 * @mbggenerated Sat Aug 06 18:19:23 CST 2016
 */
@Mapper
public interface UploadFileMapper extends BaseMapper<UploadFile, UploadFileExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    int countByExample(UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    int deleteByExample(UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    @Delete({
        "delete from upload_file",
        "where uploadFileId = #{uploadFileId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer uploadFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    @Insert({
        "insert into upload_file (uploadFileId, batchNo, ",
        "fileName, fileSuffix, ",
        "fileGuid, fileUrl, ",
        "`status`, createTime, ",
        "updateTime)",
        "values (#{uploadFileId,jdbcType=INTEGER}, #{batchNo,jdbcType=VARCHAR}, ",
        "#{fileName,jdbcType=VARCHAR}, #{fileSuffix,jdbcType=VARCHAR}, ",
        "#{fileGuid,jdbcType=VARCHAR}, #{fileUrl,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(UploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    int insertSelective(UploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    List<UploadFile> selectByExample(UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    @Select({
        "select",
        "uploadFileId, batchNo, fileName, fileSuffix, fileGuid, fileUrl, `status`, createTime, ",
        "updateTime",
        "from upload_file",
        "where uploadFileId = #{uploadFileId,jdbcType=INTEGER}"
    })
    @ResultMap("cn.kemis.dao.mapper.UploadFileMapper.BaseResultMap")
    UploadFile selectByPrimaryKey(Integer uploadFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") UploadFile record, @Param("example") UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    int updateByExample(@Param("record") UploadFile record, @Param("example") UploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    int updateByPrimaryKeySelective(UploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    @Update({
        "update upload_file",
        "set batchNo = #{batchNo,jdbcType=VARCHAR},",
          "fileName = #{fileName,jdbcType=VARCHAR},",
          "fileSuffix = #{fileSuffix,jdbcType=VARCHAR},",
          "fileGuid = #{fileGuid,jdbcType=VARCHAR},",
          "fileUrl = #{fileUrl,jdbcType=VARCHAR},",
          "`status` = #{status,jdbcType=TINYINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where uploadFileId = #{uploadFileId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UploadFile record);
}