package cn.kemis.dao.mapper;

import cn.kemis.dao.BaseMapper;
import cn.kemis.domain.RevisionListDomain;
import cn.kemis.domain.StatisticSalaryDomain;
import cn.kemis.domain.StatisticsDomain;
import cn.kemis.domain.StatisticsInfoDomain;
import cn.kemis.model.WorkProcess;
import cn.kemis.model.WorkProcessExample;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table work_process
 *
 * @mbggenerated Sun Aug 14 16:50:13 CST 2016
 */
@Mapper
public interface WorkProcessMapper extends BaseMapper<WorkProcess, WorkProcessExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    int countByExample(WorkProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    int deleteByExample(WorkProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    @Delete({
        "delete from work_process",
        "where workProcessId = #{workProcessId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long workProcessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    @Insert({
        "insert into work_process (workProcessId, userId, ",
        "expressNumber, workProcess, ",
        "`status`, createTime, ",
        "updateTime)",
        "values (#{workProcessId,jdbcType=BIGINT}, #{userId,jdbcType=INTEGER}, ",
        "#{expressNumber,jdbcType=VARCHAR}, #{workProcess,jdbcType=CHAR}, ",
        "#{status,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(WorkProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    int insertSelective(WorkProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    List<WorkProcess> selectByExample(WorkProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    @Select({
        "select",
        "workProcessId, userId, expressNumber, workProcess, `status`, createTime, updateTime",
        "from work_process",
        "where workProcessId = #{workProcessId,jdbcType=BIGINT}"
    })
    @ResultMap("cn.kemis.dao.mapper.WorkProcessMapper.BaseResultMap")
    WorkProcess selectByPrimaryKey(Long workProcessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkProcess record, @Param("example") WorkProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    int updateByExample(@Param("record") WorkProcess record, @Param("example") WorkProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    int updateByPrimaryKeySelective(WorkProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    @Update({
        "update work_process",
        "set userId = #{userId,jdbcType=INTEGER},",
          "expressNumber = #{expressNumber,jdbcType=VARCHAR},",
          "workProcess = #{workProcess,jdbcType=CHAR},",
          "`status` = #{status,jdbcType=TINYINT},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where workProcessId = #{workProcessId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WorkProcess record);

    /**
     * 计件统计 查询个数
     */
    int countUser(Map<String, Object> paramMap);

    /**
     * 计件统计查询
     */
    List<StatisticsDomain> selectInfoByMap(Map<String, Object> paramMap);

    int countWorkProcessInfoByMap(Map<String, Object> paramMap);
    /**
     * 计件详情
     * @param paramMap
     * @return
     */
    List<StatisticsInfoDomain> selectWorkProcessInfoByMap(Map<String, Object> paramMap);

    /**
     * 根据expressNumber查询工序列表
     * @param paramMap
     * @return list
     */
    List<RevisionListDomain> revisionList(Map<String, Object> paramMap);

    /**
     * 用户统计计件计费
     * @param paramMap
     * @return
     */
    List<StatisticsDomain> countProcessForSalary(Map<String, Object> paramMap);

    /**
     * 工资统计 查询个数
     */
    int countSalaryByMap(Map<String, Object> paramMap);

    /**
     * 工资统计查询
     */
    List<StatisticSalaryDomain> selectSalaryByMap(Map<String, Object> paramMap);

    /**
     * 计件统计查询 工资统计查询
     */
    List<StatisticsDomain> selectInfoForSalaryByMap(Map<String, Object> paramMap);

}