package cn.kemis.domain;

import cn.kemis.model.SysRole;
import cn.kemis.model.SysUser;

import java.util.Date;
import java.util.List;

/**
 * @author 刘体阳 jefferlzu@gmail.com
 *         Created on 2016-11-27
 */
public class SysUserDomain extends SysUser {
    private List<SysRole> roleList;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @param sysUserId
     * @param username
     * @param userCode
     * @param realName
     * @param mobile
     * @param email
     * @param address
     * @param avatar
     * @param loginCount
     * @param lastLogin
     * @param status
     * @param createTime
     * @param updateTime
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    public SysUserDomain(Integer sysUserId, String username, String userCode, String realName,
                         String mobile, String email, String address, String avatar, Integer loginCount, Date lastLogin,
                         Byte status, Date createTime, Date updateTime) {
        super(sysUserId, username, null, userCode, realName, mobile, email, address, avatar, loginCount, lastLogin,
                status, createTime, updateTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    public SysUserDomain() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Aug 18 00:35:42 CST 2016
     */
    public SysUserDomain(List<SysRole> roleList) {
        this.roleList = roleList;
    }

    public List<SysRole> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<SysRole> roleList) {
        this.roleList = roleList;
    }
}
