package cn.kemis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExpressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public ExpressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExpressIdIsNull() {
            addCriterion("expressId is null");
            return (Criteria) this;
        }

        public Criteria andExpressIdIsNotNull() {
            addCriterion("expressId is not null");
            return (Criteria) this;
        }

        public Criteria andExpressIdEqualTo(Long value) {
            addCriterion("expressId =", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdNotEqualTo(Long value) {
            addCriterion("expressId <>", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdGreaterThan(Long value) {
            addCriterion("expressId >", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("expressId >=", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdLessThan(Long value) {
            addCriterion("expressId <", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdLessThanOrEqualTo(Long value) {
            addCriterion("expressId <=", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdIn(List<Long> values) {
            addCriterion("expressId in", values, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdNotIn(List<Long> values) {
            addCriterion("expressId not in", values, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdBetween(Long value1, Long value2) {
            addCriterion("expressId between", value1, value2, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdNotBetween(Long value1, Long value2) {
            addCriterion("expressId not between", value1, value2, "expressId");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNull() {
            addCriterion("batchNo is null");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNotNull() {
            addCriterion("batchNo is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNoEqualTo(String value) {
            addCriterion("batchNo =", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotEqualTo(String value) {
            addCriterion("batchNo <>", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThan(String value) {
            addCriterion("batchNo >", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThanOrEqualTo(String value) {
            addCriterion("batchNo >=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThan(String value) {
            addCriterion("batchNo <", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThanOrEqualTo(String value) {
            addCriterion("batchNo <=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLike(String value) {
            addCriterion("batchNo like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotLike(String value) {
            addCriterion("batchNo not like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoIn(List<String> values) {
            addCriterion("batchNo in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotIn(List<String> values) {
            addCriterion("batchNo not in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoBetween(String value1, String value2) {
            addCriterion("batchNo between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotBetween(String value1, String value2) {
            addCriterion("batchNo not between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyIsNull() {
            addCriterion("expressCompany is null");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyIsNotNull() {
            addCriterion("expressCompany is not null");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyEqualTo(String value) {
            addCriterion("expressCompany =", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyNotEqualTo(String value) {
            addCriterion("expressCompany <>", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyGreaterThan(String value) {
            addCriterion("expressCompany >", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("expressCompany >=", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyLessThan(String value) {
            addCriterion("expressCompany <", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyLessThanOrEqualTo(String value) {
            addCriterion("expressCompany <=", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyLike(String value) {
            addCriterion("expressCompany like", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyNotLike(String value) {
            addCriterion("expressCompany not like", value, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyIn(List<String> values) {
            addCriterion("expressCompany in", values, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyNotIn(List<String> values) {
            addCriterion("expressCompany not in", values, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyBetween(String value1, String value2) {
            addCriterion("expressCompany between", value1, value2, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressCompanyNotBetween(String value1, String value2) {
            addCriterion("expressCompany not between", value1, value2, "expressCompany");
            return (Criteria) this;
        }

        public Criteria andExpressNumberIsNull() {
            addCriterion("expressNumber is null");
            return (Criteria) this;
        }

        public Criteria andExpressNumberIsNotNull() {
            addCriterion("expressNumber is not null");
            return (Criteria) this;
        }

        public Criteria andExpressNumberEqualTo(String value) {
            addCriterion("expressNumber =", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberNotEqualTo(String value) {
            addCriterion("expressNumber <>", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberGreaterThan(String value) {
            addCriterion("expressNumber >", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberGreaterThanOrEqualTo(String value) {
            addCriterion("expressNumber >=", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberLessThan(String value) {
            addCriterion("expressNumber <", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberLessThanOrEqualTo(String value) {
            addCriterion("expressNumber <=", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberLike(String value) {
            addCriterion("expressNumber like", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberNotLike(String value) {
            addCriterion("expressNumber not like", value, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberIn(List<String> values) {
            addCriterion("expressNumber in", values, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberNotIn(List<String> values) {
            addCriterion("expressNumber not in", values, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberBetween(String value1, String value2) {
            addCriterion("expressNumber between", value1, value2, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andExpressNumberNotBetween(String value1, String value2) {
            addCriterion("expressNumber not between", value1, value2, "expressNumber");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andDeliveryIsNull() {
            addCriterion("delivery is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIsNotNull() {
            addCriterion("delivery is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryEqualTo(String value) {
            addCriterion("delivery =", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryNotEqualTo(String value) {
            addCriterion("delivery <>", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryGreaterThan(String value) {
            addCriterion("delivery >", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryGreaterThanOrEqualTo(String value) {
            addCriterion("delivery >=", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryLessThan(String value) {
            addCriterion("delivery <", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryLessThanOrEqualTo(String value) {
            addCriterion("delivery <=", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryLike(String value) {
            addCriterion("delivery like", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryNotLike(String value) {
            addCriterion("delivery not like", value, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryIn(List<String> values) {
            addCriterion("delivery in", values, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryNotIn(List<String> values) {
            addCriterion("delivery not in", values, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryBetween(String value1, String value2) {
            addCriterion("delivery between", value1, value2, "delivery");
            return (Criteria) this;
        }

        public Criteria andDeliveryNotBetween(String value1, String value2) {
            addCriterion("delivery not between", value1, value2, "delivery");
            return (Criteria) this;
        }

        public Criteria andExportTagIsNull() {
            addCriterion("exportTag is null");
            return (Criteria) this;
        }

        public Criteria andExportTagIsNotNull() {
            addCriterion("exportTag is not null");
            return (Criteria) this;
        }

        public Criteria andExportTagEqualTo(Boolean value) {
            addCriterion("exportTag =", value, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagNotEqualTo(Boolean value) {
            addCriterion("exportTag <>", value, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagGreaterThan(Boolean value) {
            addCriterion("exportTag >", value, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("exportTag >=", value, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagLessThan(Boolean value) {
            addCriterion("exportTag <", value, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagLessThanOrEqualTo(Boolean value) {
            addCriterion("exportTag <=", value, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagIn(List<Boolean> values) {
            addCriterion("exportTag in", values, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagNotIn(List<Boolean> values) {
            addCriterion("exportTag not in", values, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagBetween(Boolean value1, Boolean value2) {
            addCriterion("exportTag between", value1, value2, "exportTag");
            return (Criteria) this;
        }

        public Criteria andExportTagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("exportTag not between", value1, value2, "exportTag");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(String value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(String value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(String value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(String value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(String value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(String value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLike(String value) {
            addCriterion("weight like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotLike(String value) {
            addCriterion("weight not like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<String> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<String> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(String value1, String value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(String value1, String value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeIsNull() {
            addCriterion("expressConsignee is null");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeIsNotNull() {
            addCriterion("expressConsignee is not null");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeEqualTo(String value) {
            addCriterion("expressConsignee =", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeNotEqualTo(String value) {
            addCriterion("expressConsignee <>", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeGreaterThan(String value) {
            addCriterion("expressConsignee >", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeGreaterThanOrEqualTo(String value) {
            addCriterion("expressConsignee >=", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeLessThan(String value) {
            addCriterion("expressConsignee <", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeLessThanOrEqualTo(String value) {
            addCriterion("expressConsignee <=", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeLike(String value) {
            addCriterion("expressConsignee like", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeNotLike(String value) {
            addCriterion("expressConsignee not like", value, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeIn(List<String> values) {
            addCriterion("expressConsignee in", values, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeNotIn(List<String> values) {
            addCriterion("expressConsignee not in", values, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeBetween(String value1, String value2) {
            addCriterion("expressConsignee between", value1, value2, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressConsigneeNotBetween(String value1, String value2) {
            addCriterion("expressConsignee not between", value1, value2, "expressConsignee");
            return (Criteria) this;
        }

        public Criteria andExpressMobileIsNull() {
            addCriterion("expressMobile is null");
            return (Criteria) this;
        }

        public Criteria andExpressMobileIsNotNull() {
            addCriterion("expressMobile is not null");
            return (Criteria) this;
        }

        public Criteria andExpressMobileEqualTo(String value) {
            addCriterion("expressMobile =", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileNotEqualTo(String value) {
            addCriterion("expressMobile <>", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileGreaterThan(String value) {
            addCriterion("expressMobile >", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileGreaterThanOrEqualTo(String value) {
            addCriterion("expressMobile >=", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileLessThan(String value) {
            addCriterion("expressMobile <", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileLessThanOrEqualTo(String value) {
            addCriterion("expressMobile <=", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileLike(String value) {
            addCriterion("expressMobile like", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileNotLike(String value) {
            addCriterion("expressMobile not like", value, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileIn(List<String> values) {
            addCriterion("expressMobile in", values, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileNotIn(List<String> values) {
            addCriterion("expressMobile not in", values, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileBetween(String value1, String value2) {
            addCriterion("expressMobile between", value1, value2, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressMobileNotBetween(String value1, String value2) {
            addCriterion("expressMobile not between", value1, value2, "expressMobile");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdIsNull() {
            addCriterion("expressSchoolId is null");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdIsNotNull() {
            addCriterion("expressSchoolId is not null");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdEqualTo(String value) {
            addCriterion("expressSchoolId =", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdNotEqualTo(String value) {
            addCriterion("expressSchoolId <>", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdGreaterThan(String value) {
            addCriterion("expressSchoolId >", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdGreaterThanOrEqualTo(String value) {
            addCriterion("expressSchoolId >=", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdLessThan(String value) {
            addCriterion("expressSchoolId <", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdLessThanOrEqualTo(String value) {
            addCriterion("expressSchoolId <=", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdLike(String value) {
            addCriterion("expressSchoolId like", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdNotLike(String value) {
            addCriterion("expressSchoolId not like", value, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdIn(List<String> values) {
            addCriterion("expressSchoolId in", values, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdNotIn(List<String> values) {
            addCriterion("expressSchoolId not in", values, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdBetween(String value1, String value2) {
            addCriterion("expressSchoolId between", value1, value2, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIdNotBetween(String value1, String value2) {
            addCriterion("expressSchoolId not between", value1, value2, "expressSchoolId");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIsNull() {
            addCriterion("expressSchool is null");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIsNotNull() {
            addCriterion("expressSchool is not null");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolEqualTo(String value) {
            addCriterion("expressSchool =", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolNotEqualTo(String value) {
            addCriterion("expressSchool <>", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolGreaterThan(String value) {
            addCriterion("expressSchool >", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("expressSchool >=", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolLessThan(String value) {
            addCriterion("expressSchool <", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolLessThanOrEqualTo(String value) {
            addCriterion("expressSchool <=", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolLike(String value) {
            addCriterion("expressSchool like", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolNotLike(String value) {
            addCriterion("expressSchool not like", value, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolIn(List<String> values) {
            addCriterion("expressSchool in", values, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolNotIn(List<String> values) {
            addCriterion("expressSchool not in", values, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolBetween(String value1, String value2) {
            addCriterion("expressSchool between", value1, value2, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressSchoolNotBetween(String value1, String value2) {
            addCriterion("expressSchool not between", value1, value2, "expressSchool");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceIsNull() {
            addCriterion("expressProvince is null");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceIsNotNull() {
            addCriterion("expressProvince is not null");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceEqualTo(String value) {
            addCriterion("expressProvince =", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceNotEqualTo(String value) {
            addCriterion("expressProvince <>", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceGreaterThan(String value) {
            addCriterion("expressProvince >", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("expressProvince >=", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceLessThan(String value) {
            addCriterion("expressProvince <", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceLessThanOrEqualTo(String value) {
            addCriterion("expressProvince <=", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceLike(String value) {
            addCriterion("expressProvince like", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceNotLike(String value) {
            addCriterion("expressProvince not like", value, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceIn(List<String> values) {
            addCriterion("expressProvince in", values, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceNotIn(List<String> values) {
            addCriterion("expressProvince not in", values, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceBetween(String value1, String value2) {
            addCriterion("expressProvince between", value1, value2, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressProvinceNotBetween(String value1, String value2) {
            addCriterion("expressProvince not between", value1, value2, "expressProvince");
            return (Criteria) this;
        }

        public Criteria andExpressCityIsNull() {
            addCriterion("expressCity is null");
            return (Criteria) this;
        }

        public Criteria andExpressCityIsNotNull() {
            addCriterion("expressCity is not null");
            return (Criteria) this;
        }

        public Criteria andExpressCityEqualTo(String value) {
            addCriterion("expressCity =", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityNotEqualTo(String value) {
            addCriterion("expressCity <>", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityGreaterThan(String value) {
            addCriterion("expressCity >", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityGreaterThanOrEqualTo(String value) {
            addCriterion("expressCity >=", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityLessThan(String value) {
            addCriterion("expressCity <", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityLessThanOrEqualTo(String value) {
            addCriterion("expressCity <=", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityLike(String value) {
            addCriterion("expressCity like", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityNotLike(String value) {
            addCriterion("expressCity not like", value, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityIn(List<String> values) {
            addCriterion("expressCity in", values, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityNotIn(List<String> values) {
            addCriterion("expressCity not in", values, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityBetween(String value1, String value2) {
            addCriterion("expressCity between", value1, value2, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressCityNotBetween(String value1, String value2) {
            addCriterion("expressCity not between", value1, value2, "expressCity");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictIsNull() {
            addCriterion("expressDistrict is null");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictIsNotNull() {
            addCriterion("expressDistrict is not null");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictEqualTo(String value) {
            addCriterion("expressDistrict =", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictNotEqualTo(String value) {
            addCriterion("expressDistrict <>", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictGreaterThan(String value) {
            addCriterion("expressDistrict >", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("expressDistrict >=", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictLessThan(String value) {
            addCriterion("expressDistrict <", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictLessThanOrEqualTo(String value) {
            addCriterion("expressDistrict <=", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictLike(String value) {
            addCriterion("expressDistrict like", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictNotLike(String value) {
            addCriterion("expressDistrict not like", value, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictIn(List<String> values) {
            addCriterion("expressDistrict in", values, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictNotIn(List<String> values) {
            addCriterion("expressDistrict not in", values, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictBetween(String value1, String value2) {
            addCriterion("expressDistrict between", value1, value2, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressDistrictNotBetween(String value1, String value2) {
            addCriterion("expressDistrict not between", value1, value2, "expressDistrict");
            return (Criteria) this;
        }

        public Criteria andExpressAddressIsNull() {
            addCriterion("expressAddress is null");
            return (Criteria) this;
        }

        public Criteria andExpressAddressIsNotNull() {
            addCriterion("expressAddress is not null");
            return (Criteria) this;
        }

        public Criteria andExpressAddressEqualTo(String value) {
            addCriterion("expressAddress =", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressNotEqualTo(String value) {
            addCriterion("expressAddress <>", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressGreaterThan(String value) {
            addCriterion("expressAddress >", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressGreaterThanOrEqualTo(String value) {
            addCriterion("expressAddress >=", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressLessThan(String value) {
            addCriterion("expressAddress <", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressLessThanOrEqualTo(String value) {
            addCriterion("expressAddress <=", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressLike(String value) {
            addCriterion("expressAddress like", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressNotLike(String value) {
            addCriterion("expressAddress not like", value, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressIn(List<String> values) {
            addCriterion("expressAddress in", values, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressNotIn(List<String> values) {
            addCriterion("expressAddress not in", values, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressBetween(String value1, String value2) {
            addCriterion("expressAddress between", value1, value2, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andExpressAddressNotBetween(String value1, String value2) {
            addCriterion("expressAddress not between", value1, value2, "expressAddress");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table express
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 25 20:38:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table express
     *
     * @mbggenerated Sun Sep 25 20:38:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}