package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table persistent_logins
 *
 * @mbggenerated do_not_delete_during_merge Wed Aug 03 23:17:35 CST 2016
 */
public class PersistentLogins implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.series
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private String series;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.username
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.token
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.last_used
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private Date last_used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public PersistentLogins(String series, String username, String token, Date last_used) {
        this.series = series;
        this.username = username;
        this.token = token;
        this.last_used = last_used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public PersistentLogins() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.series
     *
     * @return the value of persistent_logins.series
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.series
     *
     * @param series the value for persistent_logins.series
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.username
     *
     * @return the value of persistent_logins.username
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.username
     *
     * @param username the value for persistent_logins.username
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.token
     *
     * @return the value of persistent_logins.token
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.token
     *
     * @param token the value for persistent_logins.token
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.last_used
     *
     * @return the value of persistent_logins.last_used
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public Date getLast_used() {
        return last_used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.last_used
     *
     * @param last_used the value for persistent_logins.last_used
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public void setLast_used(Date last_used) {
        this.last_used = last_used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", series=").append(series);
        sb.append(", username=").append(username);
        sb.append(", token=").append(token);
        sb.append(", last_used=").append(last_used);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}