package cn.kemis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShipOrderGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public ShipOrderGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShipOrderGoodsIdIsNull() {
            addCriterion("shipOrderGoodsId is null");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdIsNotNull() {
            addCriterion("shipOrderGoodsId is not null");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdEqualTo(Long value) {
            addCriterion("shipOrderGoodsId =", value, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdNotEqualTo(Long value) {
            addCriterion("shipOrderGoodsId <>", value, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdGreaterThan(Long value) {
            addCriterion("shipOrderGoodsId >", value, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shipOrderGoodsId >=", value, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdLessThan(Long value) {
            addCriterion("shipOrderGoodsId <", value, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("shipOrderGoodsId <=", value, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdIn(List<Long> values) {
            addCriterion("shipOrderGoodsId in", values, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdNotIn(List<Long> values) {
            addCriterion("shipOrderGoodsId not in", values, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdBetween(Long value1, Long value2) {
            addCriterion("shipOrderGoodsId between", value1, value2, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("shipOrderGoodsId not between", value1, value2, "shipOrderGoodsId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdIsNull() {
            addCriterion("shipOrderId is null");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdIsNotNull() {
            addCriterion("shipOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdEqualTo(Long value) {
            addCriterion("shipOrderId =", value, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdNotEqualTo(Long value) {
            addCriterion("shipOrderId <>", value, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdGreaterThan(Long value) {
            addCriterion("shipOrderId >", value, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shipOrderId >=", value, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdLessThan(Long value) {
            addCriterion("shipOrderId <", value, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("shipOrderId <=", value, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdIn(List<Long> values) {
            addCriterion("shipOrderId in", values, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdNotIn(List<Long> values) {
            addCriterion("shipOrderId not in", values, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdBetween(Long value1, Long value2) {
            addCriterion("shipOrderId between", value1, value2, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andShipOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("shipOrderId not between", value1, value2, "shipOrderId");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goodsName is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goodsName is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goodsName =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goodsName <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goodsName >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goodsName >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goodsName <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goodsName <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goodsName like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goodsName not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goodsName in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goodsName not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goodsName between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goodsName not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsCountIsNull() {
            addCriterion("goodsCount is null");
            return (Criteria) this;
        }

        public Criteria andGoodsCountIsNotNull() {
            addCriterion("goodsCount is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsCountEqualTo(Short value) {
            addCriterion("goodsCount =", value, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountNotEqualTo(Short value) {
            addCriterion("goodsCount <>", value, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountGreaterThan(Short value) {
            addCriterion("goodsCount >", value, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountGreaterThanOrEqualTo(Short value) {
            addCriterion("goodsCount >=", value, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountLessThan(Short value) {
            addCriterion("goodsCount <", value, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountLessThanOrEqualTo(Short value) {
            addCriterion("goodsCount <=", value, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountIn(List<Short> values) {
            addCriterion("goodsCount in", values, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountNotIn(List<Short> values) {
            addCriterion("goodsCount not in", values, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountBetween(Short value1, Short value2) {
            addCriterion("goodsCount between", value1, value2, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andGoodsCountNotBetween(Short value1, Short value2) {
            addCriterion("goodsCount not between", value1, value2, "goodsCount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ship_order_goods
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 14 16:57:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ship_order_goods
     *
     * @mbggenerated Sun Aug 14 16:57:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}