package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ship_order_source
 *
 * @mbggenerated do_not_delete_during_merge Sun Sep 25 20:25:50 CST 2016
 */
public class ShipOrderSource implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.shipOrderSourceId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Long shipOrderSourceId;

    /**
     * Database Column Remarks:
     *   批次号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.batchNo
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.userId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.userName
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.province
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.city
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.district
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String district;

    /**
     * Database Column Remarks:
     *   学校 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.schoolId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String schoolId;

    /**
     * Database Column Remarks:
     *   学校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.school
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String school;

    /**
     * Database Column Remarks:
     *   班级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.theClass
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String theClass;

    /**
     * Database Column Remarks:
     *   收货人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.consignee
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String consignee;

    /**
     * Database Column Remarks:
     *   收货人电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.mobile
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   配送方式： EMS，普通快递
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.delivery
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String delivery;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.address
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String address;

    /**
     * Database Column Remarks:
     *   奖品总数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.totalCount
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Short totalCount;

    /**
     * Database Column Remarks:
     *   积分单位： 学豆，园丁豆
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.unitCredits
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String unitCredits;

    /**
     * Database Column Remarks:
     *   教师科目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.subject
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String subject;

    /**
     * Database Column Remarks:
     *   是否校园大使 0 否 1 是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.campusAmbassador
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Boolean campusAmbassador;

    /**
     * Database Column Remarks:
     *   快递单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.expressId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Long expressId;

    /**
     * Database Column Remarks:
     *   状态 数据导入时 默认值 0 默认值 处理后值为 1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.status
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.createTime
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.updateTime
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   奖品明细 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order_source.shipGoods
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private String shipGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ship_order_source
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_source
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public ShipOrderSource(Long shipOrderSourceId, String batchNo, String userId, String userName, String province, String city, String district, String schoolId, String school, String theClass, String consignee, String mobile, String delivery, String address, Short totalCount, String unitCredits, String subject, Boolean campusAmbassador, Long expressId, Byte status, Date createTime, Date updateTime, String shipGoods) {
        this.shipOrderSourceId = shipOrderSourceId;
        this.batchNo = batchNo;
        this.userId = userId;
        this.userName = userName;
        this.province = province;
        this.city = city;
        this.district = district;
        this.schoolId = schoolId;
        this.school = school;
        this.theClass = theClass;
        this.consignee = consignee;
        this.mobile = mobile;
        this.delivery = delivery;
        this.address = address;
        this.totalCount = totalCount;
        this.unitCredits = unitCredits;
        this.subject = subject;
        this.campusAmbassador = campusAmbassador;
        this.expressId = expressId;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.shipGoods = shipGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_source
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public ShipOrderSource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.shipOrderSourceId
     *
     * @return the value of ship_order_source.shipOrderSourceId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Long getShipOrderSourceId() {
        return shipOrderSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.shipOrderSourceId
     *
     * @param shipOrderSourceId the value for ship_order_source.shipOrderSourceId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setShipOrderSourceId(Long shipOrderSourceId) {
        this.shipOrderSourceId = shipOrderSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.batchNo
     *
     * @return the value of ship_order_source.batchNo
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.batchNo
     *
     * @param batchNo the value for ship_order_source.batchNo
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.userId
     *
     * @return the value of ship_order_source.userId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.userId
     *
     * @param userId the value for ship_order_source.userId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.userName
     *
     * @return the value of ship_order_source.userName
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.userName
     *
     * @param userName the value for ship_order_source.userName
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.province
     *
     * @return the value of ship_order_source.province
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.province
     *
     * @param province the value for ship_order_source.province
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.city
     *
     * @return the value of ship_order_source.city
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.city
     *
     * @param city the value for ship_order_source.city
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.district
     *
     * @return the value of ship_order_source.district
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.district
     *
     * @param district the value for ship_order_source.district
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.schoolId
     *
     * @return the value of ship_order_source.schoolId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.schoolId
     *
     * @param schoolId the value for ship_order_source.schoolId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.school
     *
     * @return the value of ship_order_source.school
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.school
     *
     * @param school the value for ship_order_source.school
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.theClass
     *
     * @return the value of ship_order_source.theClass
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getTheClass() {
        return theClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.theClass
     *
     * @param theClass the value for ship_order_source.theClass
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setTheClass(String theClass) {
        this.theClass = theClass == null ? null : theClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.consignee
     *
     * @return the value of ship_order_source.consignee
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.consignee
     *
     * @param consignee the value for ship_order_source.consignee
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.mobile
     *
     * @return the value of ship_order_source.mobile
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.mobile
     *
     * @param mobile the value for ship_order_source.mobile
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.delivery
     *
     * @return the value of ship_order_source.delivery
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.delivery
     *
     * @param delivery the value for ship_order_source.delivery
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setDelivery(String delivery) {
        this.delivery = delivery == null ? null : delivery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.address
     *
     * @return the value of ship_order_source.address
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.address
     *
     * @param address the value for ship_order_source.address
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.totalCount
     *
     * @return the value of ship_order_source.totalCount
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Short getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.totalCount
     *
     * @param totalCount the value for ship_order_source.totalCount
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setTotalCount(Short totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.unitCredits
     *
     * @return the value of ship_order_source.unitCredits
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getUnitCredits() {
        return unitCredits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.unitCredits
     *
     * @param unitCredits the value for ship_order_source.unitCredits
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setUnitCredits(String unitCredits) {
        this.unitCredits = unitCredits == null ? null : unitCredits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.subject
     *
     * @return the value of ship_order_source.subject
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.subject
     *
     * @param subject the value for ship_order_source.subject
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.campusAmbassador
     *
     * @return the value of ship_order_source.campusAmbassador
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Boolean getCampusAmbassador() {
        return campusAmbassador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.campusAmbassador
     *
     * @param campusAmbassador the value for ship_order_source.campusAmbassador
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setCampusAmbassador(Boolean campusAmbassador) {
        this.campusAmbassador = campusAmbassador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.expressId
     *
     * @return the value of ship_order_source.expressId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Long getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.expressId
     *
     * @param expressId the value for ship_order_source.expressId
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setExpressId(Long expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.status
     *
     * @return the value of ship_order_source.status
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.status
     *
     * @param status the value for ship_order_source.status
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.createTime
     *
     * @return the value of ship_order_source.createTime
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.createTime
     *
     * @param createTime the value for ship_order_source.createTime
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.updateTime
     *
     * @return the value of ship_order_source.updateTime
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.updateTime
     *
     * @param updateTime the value for ship_order_source.updateTime
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order_source.shipGoods
     *
     * @return the value of ship_order_source.shipGoods
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public String getShipGoods() {
        return shipGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order_source.shipGoods
     *
     * @param shipGoods the value for ship_order_source.shipGoods
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    public void setShipGoods(String shipGoods) {
        this.shipGoods = shipGoods == null ? null : shipGoods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order_source
     *
     * @mbggenerated Sun Sep 25 20:25:50 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shipOrderSourceId=").append(shipOrderSourceId);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", schoolId=").append(schoolId);
        sb.append(", school=").append(school);
        sb.append(", theClass=").append(theClass);
        sb.append(", consignee=").append(consignee);
        sb.append(", mobile=").append(mobile);
        sb.append(", delivery=").append(delivery);
        sb.append(", address=").append(address);
        sb.append(", totalCount=").append(totalCount);
        sb.append(", unitCredits=").append(unitCredits);
        sb.append(", subject=").append(subject);
        sb.append(", campusAmbassador=").append(campusAmbassador);
        sb.append(", expressId=").append(expressId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", shipGoods=").append(shipGoods);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}