package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ship_order
 *
 * @mbggenerated do_not_delete_during_merge Sun Sep 25 20:32:23 CST 2016
 */
public class ShipOrder implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.shipOrderId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Long shipOrderId;

    /**
     * Database Column Remarks:
     *   批次号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.batchNo
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.userId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.userName
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.province
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.city
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.district
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String district;

    /**
     * Database Column Remarks:
     *   学校 ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.schoolId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String schoolId;

    /**
     * Database Column Remarks:
     *   学校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.school
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String school;

    /**
     * Database Column Remarks:
     *   班级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.theClass
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String theClass;

    /**
     * Database Column Remarks:
     *   收货人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.consignee
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String consignee;

    /**
     * Database Column Remarks:
     *   收货人电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.mobile
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   配送方式： EMS，普通快递
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.delivery
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String delivery;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.address
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String address;

    /**
     * Database Column Remarks:
     *   奖品总数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.totalCount
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Short totalCount;

    /**
     * Database Column Remarks:
     *   积分单位： 学豆，园丁豆
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.unitCredits
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String unitCredits;

    /**
     * Database Column Remarks:
     *   教师科目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.subject
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private String subject;

    /**
     * Database Column Remarks:
     *   是否校园大使 0 否 1 是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.campusAmbassador
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Boolean campusAmbassador;

    /**
     * Database Column Remarks:
     *   快递单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.expressId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Long expressId;

    /**
     * Database Column Remarks:
     *   是打印过快递单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.printExpress
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Boolean printExpress;

    /**
     * Database Column Remarks:
     *   是否导出过快递单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.outExpress
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Boolean outExpress;

    /**
     * Database Column Remarks:
     *   是否导出校验老师单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.outVerify
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Boolean outVerify;

    /**
     * Database Column Remarks:
     *   是否是老师的标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.teacherTag
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Boolean teacherTag;

    /**
     * Database Column Remarks:
     *   是否大包裹
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.bigPackage
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Boolean bigPackage;

    /**
     * Database Column Remarks:
     *   状态 数据导入时 老师默认值 0 学生默认值 1，老师单校验后值为1。仅值为1的可以打印快递单发货。值为2已发货，3已签收，4异常件。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.status
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.createTime
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship_order.updateTime
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private Date updateTime;

    private Integer sourceOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ship_order
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public ShipOrder(Long shipOrderId, String batchNo, String userId, String userName, String province, String city, String district, String schoolId, String school, String theClass, String consignee, String mobile, String delivery, String address, Short totalCount, String unitCredits, String subject, Boolean campusAmbassador, Long expressId, Boolean printExpress, Boolean outExpress, Boolean outVerify, Boolean teacherTag, Boolean bigPackage, Byte status, Date createTime, Date updateTime) {
        this.shipOrderId = shipOrderId;
        this.batchNo = batchNo;
        this.userId = userId;
        this.userName = userName;
        this.province = province;
        this.city = city;
        this.district = district;
        this.schoolId = schoolId;
        this.school = school;
        this.theClass = theClass;
        this.consignee = consignee;
        this.mobile = mobile;
        this.delivery = delivery;
        this.address = address;
        this.totalCount = totalCount;
        this.unitCredits = unitCredits;
        this.subject = subject;
        this.campusAmbassador = campusAmbassador;
        this.expressId = expressId;
        this.printExpress = printExpress;
        this.outExpress = outExpress;
        this.outVerify = outVerify;
        this.teacherTag = teacherTag;
        this.bigPackage = bigPackage;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.sourceOrder = sourceOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public ShipOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.shipOrderId
     *
     * @return the value of ship_order.shipOrderId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Long getShipOrderId() {
        return shipOrderId;
    }

    public void setSourceOrder(Integer sourceOrder){this.sourceOrder = sourceOrder;}

    public Integer getSourceOrder(){
        return sourceOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.shipOrderId
     *
     * @param shipOrderId the value for ship_order.shipOrderId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setShipOrderId(Long shipOrderId) {
        this.shipOrderId = shipOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.batchNo
     *
     * @return the value of ship_order.batchNo
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */

    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.batchNo
     *
     * @param batchNo the value for ship_order.batchNo
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.userId
     *
     * @return the value of ship_order.userId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.userId
     *
     * @param userId the value for ship_order.userId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.userName
     *
     * @return the value of ship_order.userName
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.userName
     *
     * @param userName the value for ship_order.userName
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.province
     *
     * @return the value of ship_order.province
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.province
     *
     * @param province the value for ship_order.province
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.city
     *
     * @return the value of ship_order.city
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.city
     *
     * @param city the value for ship_order.city
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.district
     *
     * @return the value of ship_order.district
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.district
     *
     * @param district the value for ship_order.district
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.schoolId
     *
     * @return the value of ship_order.schoolId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.schoolId
     *
     * @param schoolId the value for ship_order.schoolId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.school
     *
     * @return the value of ship_order.school
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.school
     *
     * @param school the value for ship_order.school
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.theClass
     *
     * @return the value of ship_order.theClass
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getTheClass() {
        return theClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.theClass
     *
     * @param theClass the value for ship_order.theClass
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setTheClass(String theClass) {
        this.theClass = theClass == null ? null : theClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.consignee
     *
     * @return the value of ship_order.consignee
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.consignee
     *
     * @param consignee the value for ship_order.consignee
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.mobile
     *
     * @return the value of ship_order.mobile
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.mobile
     *
     * @param mobile the value for ship_order.mobile
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.delivery
     *
     * @return the value of ship_order.delivery
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.delivery
     *
     * @param delivery the value for ship_order.delivery
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setDelivery(String delivery) {
        this.delivery = delivery == null ? null : delivery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.address
     *
     * @return the value of ship_order.address
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.address
     *
     * @param address the value for ship_order.address
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.totalCount
     *
     * @return the value of ship_order.totalCount
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Short getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.totalCount
     *
     * @param totalCount the value for ship_order.totalCount
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setTotalCount(Short totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.unitCredits
     *
     * @return the value of ship_order.unitCredits
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getUnitCredits() {
        return unitCredits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.unitCredits
     *
     * @param unitCredits the value for ship_order.unitCredits
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setUnitCredits(String unitCredits) {
        this.unitCredits = unitCredits == null ? null : unitCredits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.subject
     *
     * @return the value of ship_order.subject
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.subject
     *
     * @param subject the value for ship_order.subject
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.campusAmbassador
     *
     * @return the value of ship_order.campusAmbassador
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Boolean getCampusAmbassador() {
        return campusAmbassador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.campusAmbassador
     *
     * @param campusAmbassador the value for ship_order.campusAmbassador
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setCampusAmbassador(Boolean campusAmbassador) {
        this.campusAmbassador = campusAmbassador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.expressId
     *
     * @return the value of ship_order.expressId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Long getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.expressId
     *
     * @param expressId the value for ship_order.expressId
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setExpressId(Long expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.printExpress
     *
     * @return the value of ship_order.printExpress
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Boolean getPrintExpress() {
        return printExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.printExpress
     *
     * @param printExpress the value for ship_order.printExpress
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setPrintExpress(Boolean printExpress) {
        this.printExpress = printExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.outExpress
     *
     * @return the value of ship_order.outExpress
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Boolean getOutExpress() {
        return outExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.outExpress
     *
     * @param outExpress the value for ship_order.outExpress
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setOutExpress(Boolean outExpress) {
        this.outExpress = outExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.outVerify
     *
     * @return the value of ship_order.outVerify
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Boolean getOutVerify() {
        return outVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.outVerify
     *
     * @param outVerify the value for ship_order.outVerify
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setOutVerify(Boolean outVerify) {
        this.outVerify = outVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.teacherTag
     *
     * @return the value of ship_order.teacherTag
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Boolean getTeacherTag() {
        return teacherTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.teacherTag
     *
     * @param teacherTag the value for ship_order.teacherTag
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setTeacherTag(Boolean teacherTag) {
        this.teacherTag = teacherTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.bigPackage
     *
     * @return the value of ship_order.bigPackage
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Boolean getBigPackage() {
        return bigPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.bigPackage
     *
     * @param bigPackage the value for ship_order.bigPackage
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setBigPackage(Boolean bigPackage) {
        this.bigPackage = bigPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.status
     *
     * @return the value of ship_order.status
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.status
     *
     * @param status the value for ship_order.status
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.createTime
     *
     * @return the value of ship_order.createTime
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.createTime
     *
     * @param createTime the value for ship_order.createTime
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship_order.updateTime
     *
     * @return the value of ship_order.updateTime
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship_order.updateTime
     *
     * @param updateTime the value for ship_order.updateTime
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ship_order
     *
     * @mbggenerated Sun Sep 25 20:32:23 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shipOrderId=").append(shipOrderId);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", schoolId=").append(schoolId);
        sb.append(", school=").append(school);
        sb.append(", theClass=").append(theClass);
        sb.append(", consignee=").append(consignee);
        sb.append(", mobile=").append(mobile);
        sb.append(", delivery=").append(delivery);
        sb.append(", address=").append(address);
        sb.append(", totalCount=").append(totalCount);
        sb.append(", unitCredits=").append(unitCredits);
        sb.append(", subject=").append(subject);
        sb.append(", campusAmbassador=").append(campusAmbassador);
        sb.append(", expressId=").append(expressId);
        sb.append(", printExpress=").append(printExpress);
        sb.append(", outExpress=").append(outExpress);
        sb.append(", outVerify=").append(outVerify);
        sb.append(", teacherTag=").append(teacherTag);
        sb.append(", bigPackage=").append(bigPackage);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}