package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_configuration
 *
 * @mbggenerated do_not_delete_during_merge Sun Aug 28 18:48:29 CST 2016
 */
public class SysConfiguration implements Serializable {
    /**
     * Database Column Remarks:
     *   键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_configuration.propertyKey
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private String propertyKey;

    /**
     * Database Column Remarks:
     *   值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_configuration.propertyValue
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private String propertyValue;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_configuration.desc
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private String desc;

    /**
     * Database Column Remarks:
     *   状态 数据导入时 老师默认值 0 学生默认值 1，老师单校验后值为1。仅值为1的可以打印快递单发货。值为2已发货，3已签收，4异常件。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_configuration.status
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_configuration.createTime
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_configuration.updateTime
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_configuration
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_configuration
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public SysConfiguration(String propertyKey, String propertyValue, String desc, Byte status, Date createTime, Date updateTime) {
        this.propertyKey = propertyKey;
        this.propertyValue = propertyValue;
        this.desc = desc;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_configuration
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public SysConfiguration() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_configuration.propertyKey
     *
     * @return the value of sys_configuration.propertyKey
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public String getPropertyKey() {
        return propertyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_configuration.propertyKey
     *
     * @param propertyKey the value for sys_configuration.propertyKey
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public void setPropertyKey(String propertyKey) {
        this.propertyKey = propertyKey == null ? null : propertyKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_configuration.propertyValue
     *
     * @return the value of sys_configuration.propertyValue
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_configuration.propertyValue
     *
     * @param propertyValue the value for sys_configuration.propertyValue
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_configuration.desc
     *
     * @return the value of sys_configuration.desc
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_configuration.desc
     *
     * @param desc the value for sys_configuration.desc
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_configuration.status
     *
     * @return the value of sys_configuration.status
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_configuration.status
     *
     * @param status the value for sys_configuration.status
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_configuration.createTime
     *
     * @return the value of sys_configuration.createTime
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_configuration.createTime
     *
     * @param createTime the value for sys_configuration.createTime
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_configuration.updateTime
     *
     * @return the value of sys_configuration.updateTime
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_configuration.updateTime
     *
     * @param updateTime the value for sys_configuration.updateTime
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_configuration
     *
     * @mbggenerated Sun Aug 28 18:48:29 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", propertyKey=").append(propertyKey);
        sb.append(", propertyValue=").append(propertyValue);
        sb.append(", desc=").append(desc);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}