package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_module
 *
 * @mbggenerated do_not_delete_during_merge Thu Aug 18 00:36:46 CST 2016
 */
public class SysModule implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.sysModuleId
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private Integer sysModuleId;

    /**
     * Database Column Remarks:
     *   模块名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.moduleName
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private String moduleName;

    /**
     * Database Column Remarks:
     *   父角色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.moduleParentId
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private Integer moduleParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.moduleUrl
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private String moduleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.status
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.createTime
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_module.updateTime
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_module
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public SysModule(Integer sysModuleId, String moduleName, Integer moduleParentId, String moduleUrl, Byte status, Date createTime, Date updateTime) {
        this.sysModuleId = sysModuleId;
        this.moduleName = moduleName;
        this.moduleParentId = moduleParentId;
        this.moduleUrl = moduleUrl;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public SysModule() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.sysModuleId
     *
     * @return the value of sys_module.sysModuleId
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public Integer getSysModuleId() {
        return sysModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.sysModuleId
     *
     * @param sysModuleId the value for sys_module.sysModuleId
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setSysModuleId(Integer sysModuleId) {
        this.sysModuleId = sysModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.moduleName
     *
     * @return the value of sys_module.moduleName
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.moduleName
     *
     * @param moduleName the value for sys_module.moduleName
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.moduleParentId
     *
     * @return the value of sys_module.moduleParentId
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public Integer getModuleParentId() {
        return moduleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.moduleParentId
     *
     * @param moduleParentId the value for sys_module.moduleParentId
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setModuleParentId(Integer moduleParentId) {
        this.moduleParentId = moduleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.moduleUrl
     *
     * @return the value of sys_module.moduleUrl
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.moduleUrl
     *
     * @param moduleUrl the value for sys_module.moduleUrl
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.status
     *
     * @return the value of sys_module.status
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.status
     *
     * @param status the value for sys_module.status
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.createTime
     *
     * @return the value of sys_module.createTime
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.createTime
     *
     * @param createTime the value for sys_module.createTime
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_module.updateTime
     *
     * @return the value of sys_module.updateTime
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_module.updateTime
     *
     * @param updateTime the value for sys_module.updateTime
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbggenerated Thu Aug 18 00:36:46 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysModuleId=").append(sysModuleId);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", moduleParentId=").append(moduleParentId);
        sb.append(", moduleUrl=").append(moduleUrl);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}