package cn.kemis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_has_sys_module
 *
 * @mbggenerated do_not_delete_during_merge Wed Aug 03 23:17:35 CST 2016
 */
public class SysRoleHasSysModuleKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_has_sys_module.roleId
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_has_sys_module.moduleId
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_has_sys_module
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_has_sys_module
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public SysRoleHasSysModuleKey(Integer roleId, Integer moduleId) {
        this.roleId = roleId;
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_has_sys_module
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public SysRoleHasSysModuleKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_has_sys_module.roleId
     *
     * @return the value of sys_role_has_sys_module.roleId
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_has_sys_module.roleId
     *
     * @param roleId the value for sys_role_has_sys_module.roleId
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_has_sys_module.moduleId
     *
     * @return the value of sys_role_has_sys_module.moduleId
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_has_sys_module.moduleId
     *
     * @param moduleId the value for sys_role_has_sys_module.moduleId
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_has_sys_module
     *
     * @mbggenerated Wed Aug 03 23:17:35 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", moduleId=").append(moduleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}