package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table upload_file
 *
 * @mbggenerated do_not_delete_during_merge Sat Aug 06 18:19:23 CST 2016
 */
public class UploadFile implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.uploadFileId
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private Integer uploadFileId;

    /**
     * Database Column Remarks:
     *   批次号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.batchNo
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.fileName
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   文件后缀
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.fileSuffix
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private String fileSuffix;

    /**
     * Database Column Remarks:
     *   文件全球唯一码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.fileGuid
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private String fileGuid;

    /**
     * Database Column Remarks:
     *   文件地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.fileUrl
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private String fileUrl;

    /**
     * Database Column Remarks:
     *   状态 数据导入时 老师默认值 0 学生默认值 1，老师单校验后值为1。仅值为1的可以打印快递单发货。值为2已发货，3已签收，4异常件。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.status
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.createTime
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_file.updateTime
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public UploadFile(Integer uploadFileId, String batchNo, String fileName, String fileSuffix, String fileGuid, String fileUrl, Byte status, Date createTime, Date updateTime) {
        this.uploadFileId = uploadFileId;
        this.batchNo = batchNo;
        this.fileName = fileName;
        this.fileSuffix = fileSuffix;
        this.fileGuid = fileGuid;
        this.fileUrl = fileUrl;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public UploadFile() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.uploadFileId
     *
     * @return the value of upload_file.uploadFileId
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public Integer getUploadFileId() {
        return uploadFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.uploadFileId
     *
     * @param uploadFileId the value for upload_file.uploadFileId
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setUploadFileId(Integer uploadFileId) {
        this.uploadFileId = uploadFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.batchNo
     *
     * @return the value of upload_file.batchNo
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.batchNo
     *
     * @param batchNo the value for upload_file.batchNo
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.fileName
     *
     * @return the value of upload_file.fileName
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.fileName
     *
     * @param fileName the value for upload_file.fileName
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.fileSuffix
     *
     * @return the value of upload_file.fileSuffix
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.fileSuffix
     *
     * @param fileSuffix the value for upload_file.fileSuffix
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.fileGuid
     *
     * @return the value of upload_file.fileGuid
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public String getFileGuid() {
        return fileGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.fileGuid
     *
     * @param fileGuid the value for upload_file.fileGuid
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setFileGuid(String fileGuid) {
        this.fileGuid = fileGuid == null ? null : fileGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.fileUrl
     *
     * @return the value of upload_file.fileUrl
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.fileUrl
     *
     * @param fileUrl the value for upload_file.fileUrl
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.status
     *
     * @return the value of upload_file.status
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.status
     *
     * @param status the value for upload_file.status
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.createTime
     *
     * @return the value of upload_file.createTime
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.createTime
     *
     * @param createTime the value for upload_file.createTime
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_file.updateTime
     *
     * @return the value of upload_file.updateTime
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_file.updateTime
     *
     * @param updateTime the value for upload_file.updateTime
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_file
     *
     * @mbggenerated Sat Aug 06 18:19:23 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uploadFileId=").append(uploadFileId);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileSuffix=").append(fileSuffix);
        sb.append(", fileGuid=").append(fileGuid);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}