package cn.kemis.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table work_process
 *
 * @mbggenerated do_not_delete_during_merge Sun Aug 14 16:50:13 CST 2016
 */
public class WorkProcess implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.workProcessId
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private Long workProcessId;

    /**
     * Database Column Remarks:
     *   系统用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.userId
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   物流单号ß
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.expressNumber
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private String expressNumber;

    /**
     * Database Column Remarks:
     *   工序 cutOrder 划单 pickingGoods 捡货 package 打包
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.workProcess
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private String workProcess;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.status
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.createTime
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_process.updateTime
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public WorkProcess(Long workProcessId, Integer userId, String expressNumber, String workProcess, Byte status, Date createTime, Date updateTime) {
        this.workProcessId = workProcessId;
        this.userId = userId;
        this.expressNumber = expressNumber;
        this.workProcess = workProcess;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public WorkProcess() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.workProcessId
     *
     * @return the value of work_process.workProcessId
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public Long getWorkProcessId() {
        return workProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.workProcessId
     *
     * @param workProcessId the value for work_process.workProcessId
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setWorkProcessId(Long workProcessId) {
        this.workProcessId = workProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.userId
     *
     * @return the value of work_process.userId
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.userId
     *
     * @param userId the value for work_process.userId
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.expressNumber
     *
     * @return the value of work_process.expressNumber
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.expressNumber
     *
     * @param expressNumber the value for work_process.expressNumber
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.workProcess
     *
     * @return the value of work_process.workProcess
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public String getWorkProcess() {
        return workProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.workProcess
     *
     * @param workProcess the value for work_process.workProcess
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setWorkProcess(String workProcess) {
        this.workProcess = workProcess == null ? null : workProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.status
     *
     * @return the value of work_process.status
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.status
     *
     * @param status the value for work_process.status
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.createTime
     *
     * @return the value of work_process.createTime
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.createTime
     *
     * @param createTime the value for work_process.createTime
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_process.updateTime
     *
     * @return the value of work_process.updateTime
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_process.updateTime
     *
     * @param updateTime the value for work_process.updateTime
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_process
     *
     * @mbggenerated Sun Aug 14 16:50:13 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workProcessId=").append(workProcessId);
        sb.append(", userId=").append(userId);
        sb.append(", expressNumber=").append(expressNumber);
        sb.append(", workProcess=").append(workProcess);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}